### ISSUE TITLE
Bam Pile-up error

### ISSUE THREAD

**Issue by jgockley62** [jcarrotzhang/LoLoPicker#2]
Hi, 

Despite sorting my input I keep getting an error when I run LoLoPicker_somatic.py. Code is as follows:

samtools sort -@ 32 -m 5000000000 -T Tumor_Total.sorted.bam -o Tumor_Total.sorted.bam Tumor_phased_possorted_bam.bam

samtools sort -@ 32 -m 5000000000 -T Germline_Total.sorted.bam -o Germline_Total.sorted.bam Germline_phased_possorted_bam.bam 

samtools index Tumor_Total.sorted.bam
samtools index Germline_Total.sorted.bam

python /home/jgockley/Programs/LoLoPicker/lolopicker/scripts/LoLoPicker_somatic.py --basequality 30 --phasing_mode Y -t Tumor_Total.sorted.bam
 -n Germline_Total.sorted.bam  -r genome.fa -b hg38_chrom.bed -o LoLoPicker/

#1 it runs for a little while and then throws the following error

_[bam_pileup_core] the input is not sorted (reads out of order)
Traceback (most recent call last):
  File "/home/jgockley/Programs/LoLoPicker/lolopicker/scripts/LoLoPicker_somatic.py", line 182, in <module>
    for rec in pysamstats.stat_variation(t_samfile, ref, chrom=str(bedline[0]), start=int(bedline[1]), end=int(bedline[2])):
  File "pysamstats.pyx", line 3674, in _iter_pileup_default (pysamstats.c:34825)
  File "pysam/calignmentfile.pyx", line 2213, in pysam.calignmentfile.IteratorColumnRegion.__next__ (pysam/calignmentfile.c:24146)
ValueError: error during iteration_

**Comment by jcarrotzhang** [comment]
Hi Jake,

There's a bug in pysamstats for sorting that I have been trying to contact
the developer of pysamstats to fix. Could you look at the LoLoPicker
outputs and figure out where it stopped? For now, please give a bed file
excluding the problematic regions.

Alternatively, you could use MuTect2 to make initial calls and generate a
bed file of variants called by MuTect2. Then give the bed file to
LoLoPicker for further filtering. MuTect2 has increased sensitivity but not
much improved specificity. MuTect2+LoLoPicker is the strategy I have been
using here, which is much faster and the accuracy is better when using
both. Sorry for the inconvenience and let me know how it goes!

Best,
Jian

**Comment by jgockley62** [comment]
The variant candidate bed file would just replace the interval bed file in this case?

**Comment by jcarrotzhang** [comment]
Yes, something like:

chr17 7579000 7579900

as "interval" bed file.
