### ISSUE TITLE
install error "no attribute HTSFile"

### ISSUE THREAD

**Issue by RichardCorbett** [jcarrotzhang/LoLoPicker#4]
Hi there.
I'm trying to install this on CentOS7 using Python 2.7.   Have you seen the following?  What do you recommend?

```
(python-2.7-venv) # gphost14 ~/bin/LoLoPicker $ 
pip install pysam==0.8.4
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: pysam==0.8.4 in /home/rcorbett/python-2.7-venv/lib/python2.7/site-packages (0.8.4)
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(python-2.7-venv) # gphost14 ~/bin/LoLoPicker $ 
pip install pysamstats
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: pysamstats in /home/rcorbett/python-2.7-venv/lib/python2.7/site-packages (1.1.2)
Requirement already satisfied: pysam<0.16 in /home/rcorbett/python-2.7-venv/lib/python2.7/site-packages (from pysamstats) (0.8.4)
Requirement already satisfied: numpy in /home/rcorbett/python-2.7-venv/lib/python2.7/site-packages (from pysamstats) (1.15.1)
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(python-2.7-venv) # gphost14 ~/bin/LoLoPicker $ 
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pysamstats
  File "/home/rcorbett/python-2.7-venv/lib/python2.7/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/home/rcorbett/python-2.7-venv/lib/python2.7/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libchtslib.pxd", line 2590, in init pysamstats.opt
AttributeError: 'module' object has no attribute 'HTSFile'

```

**Comment by master-noddy** [comment]
I also got the same error with python 3.6 in CentOS7

-bash-4.2$ ~/packages/Python-3.6.5/bin/python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pysamstats
  File "/data/sata_data/home/dl7/packages/Python-3.6.5/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/data/sata_data/home/dl7/packages/Python-3.6.5/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libchtslib.pxd", line 2590, in init pysamstats.opt
AttributeError: module 'pysam.libchtslib' has no attribute 'HTSFile'

**Comment by OlenaMaiakovska** [comment]
Similar problem! Hopefully there will be a solution!
